// Builds scripts/world_map_data.gd from Natural Earth 110m land (public domain):
// per continent, the land polygons clipped to the view box, simplified, projected
// (x = longitude, y = Mercator latitude, both in degrees; +y is north) plus the
// real coordinates of every campaign stop.
//   node tools/geo/make_world_map.cjs
const fs = require('fs');
const path = require('path');

const land = JSON.parse(fs.readFileSync(path.join(__dirname, 'ne_110m_land.geojson'), 'utf8'));
const OUT = path.join(__dirname, '..', '..', 'scripts', 'world_map_data.gd');
const TOLERANCE = 0.3;
const MIN_AREA = 1.5;
// Land is clipped to the view box grown by this share per side, so coasts run
// past the edge of the camera frame instead of ending in a straight cut.
const PAD = 0.35;

// View boxes [west, south, east, north]; Oceania uses 0..360 longitudes.
const REGIONS = {
  asia: { box: [60, -9, 150, 53] },
  europe: { box: [-14, 33, 48, 63] },
  africa: { box: [-21, -37, 55, 38] },
  namerica: { box: [-130, 12, -56, 57] },
  samerica: { box: [-86, -56, -32, 14] },
  oceania: { box: [108, -48, 186, -8], wrap: true },
};
// Campaign stops in campaign.gd order: [longitude, latitude].
const STOPS = {
  asia: [[105.84, 21.04], [126.99, 37.55], [105.84, 21.03], [100.49, 13.74], [78.04, 27.17], [121.5, 31.24], [138.73, 35.36], [139.75, 35.66]],
  europe: [[2.29, 48.86], [13.38, 52.52], [-0.12, 51.5], [-3.69, 40.42], [10.4, 43.72], [4.89, 52.37], [12.49, 41.89], [37.62, 55.75]],
  africa: [[31.13, 29.98], [31.22, 30.05], [31.14, 29.98], [36.82, -1.29], [-4.56, 13.91], [3.39, 6.45], [44.42, -20.25], [18.4, -33.96]],
  namerica: [[-74.04, 40.69], [-87.64, 41.88], [-73.99, 40.75], [-79.39, 43.64], [-122.35, 47.62], [-118.32, 34.13], [-88.57, 20.68], [-77.01, 38.89]],
  samerica: [[-43.21, -22.95], [-46.66, -23.56], [-72.55, -13.16], [-77.03, -12.05], [-58.38, -34.6], [-74.06, 4.61], [-43.16, -22.95], [-70.61, -33.42]],
  oceania: [[151.21, -33.86], [144.97, -37.82], [131.04, -25.34], [115.86, -31.96], [174.76, -36.85], [177.44, -17.8], [-109.35, -27.12], [149.12, -35.31]],
};

const mercator = (lat) => (180 / Math.PI) * Math.log(Math.tan(Math.PI / 4 + (lat * Math.PI) / 360));

function lerpAt(a, b, axis, value) {
  const t = (value - a[axis]) / (b[axis] - a[axis]);
  return [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t];
}

// Sutherland-Hodgman against the (convex) view box.
function clip(ring, [w, s, e, n]) {
  const edges = [
    [(p) => p[0] >= w, (a, b) => lerpAt(a, b, 0, w)],
    [(p) => p[0] <= e, (a, b) => lerpAt(a, b, 0, e)],
    [(p) => p[1] >= s, (a, b) => lerpAt(a, b, 1, s)],
    [(p) => p[1] <= n, (a, b) => lerpAt(a, b, 1, n)],
  ];
  let out = ring;
  for (const [inside, cut] of edges) {
    const input = out;
    out = [];
    for (let i = 0; i < input.length; i++) {
      const a = input[(i + input.length - 1) % input.length];
      const b = input[i];
      if (inside(b)) {
        if (!inside(a)) out.push(cut(a, b));
        out.push(b);
      } else if (inside(a)) out.push(cut(a, b));
    }
    if (!out.length) return out;
  }
  return out;
}

function segmentDistance(p, a, b) {
  const dx = b[0] - a[0];
  const dy = b[1] - a[1];
  const length = dx * dx + dy * dy;
  const t = length ? Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / length)) : 0;
  return Math.hypot(p[0] - a[0] - t * dx, p[1] - a[1] - t * dy);
}

// Douglas-Peucker on an open polyline.
function simplify(points, tolerance) {
  if (points.length < 4) return points;
  const keep = new Array(points.length).fill(false);
  keep[0] = keep[points.length - 1] = true;
  const stack = [[0, points.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    let worst = -1;
    let index = -1;
    for (let i = a + 1; i < b; i++) {
      const d = segmentDistance(points[i], points[a], points[b]);
      if (d > worst) { worst = d; index = i; }
    }
    if (worst > tolerance) {
      keep[index] = true;
      stack.push([a, index], [index, b]);
    }
  }
  return points.filter((_, i) => keep[i]);
}

const area = (ring) => Math.abs(ring.reduce((sum, p, i) => {
  const q = ring[(i + 1) % ring.length];
  return sum + p[0] * q[1] - q[0] * p[1];
}, 0) / 2);

function outerRings() {
  const result = [];
  for (const feature of land.features) {
    const g = feature.geometry;
    const polygons = g.type === 'Polygon' ? [g.coordinates] : g.coordinates;
    for (const polygon of polygons) result.push(polygon[0].slice(0, -1));
  }
  return result;
}

const fmt = (v) => Number(v.toFixed(2));
let source = '# Generated by tools/geo/make_world_map.cjs from Natural Earth 110m land (public domain).\n';
source += '# Per continent: view box [west, south, east, north] in projected degrees\n';
source += '# (x = longitude, y = Mercator latitude, +y north), land rings as flat\n';
source += '# [x0, y0, x1, y1, ...] arrays and campaign stops as [x, y] pairs.\n';
source += 'const REGIONS = {\n';
for (const [id, region] of Object.entries(REGIONS)) {
  const [w, s, e, n] = region.box;
  const box = [w, mercator(s), e, mercator(n)];
  const padX = (box[2] - box[0]) * PAD;
  const padY = (box[3] - box[1]) * PAD;
  const clipBox = [box[0] - padX, box[1] - padY, box[2] + padX, box[3] + padY];
  const polygons = [];
  for (const raw of outerRings()) {
    for (const shift of region.wrap ? [0, 360] : [0]) {
      const projected = raw.map(([lon, lat]) => [lon + shift, mercator(Math.max(-85, Math.min(85, lat)))]);
      let ring = clip(projected, clipBox);
      if (ring.length < 3) continue;
      ring = simplify([...ring, ring[0]], TOLERANCE).slice(0, -1);
      if (ring.length < 3 || area(ring) < MIN_AREA) continue;
      polygons.push(ring);
    }
  }
  const stops = STOPS[id].map(([lon, lat]) => [region.wrap && lon < 0 ? lon + 360 : lon, mercator(lat)]);
  source += `\t"${id}": {"box": [${box.map(fmt).join(', ')}],\n`;
  source += `\t\t"stops": [${stops.map((p) => `[${fmt(p[0])}, ${fmt(p[1])}]`).join(', ')}],\n`;
  source += '\t\t"land": [\n';
  for (const ring of polygons) {
    source += `\t\t\t[${ring.map((p) => `${fmt(p[0])}, ${fmt(p[1])}`).join(', ')}],\n`;
  }
  source += '\t\t]},\n';
  console.log(id, polygons.length, 'polygons', polygons.reduce((n, r) => n + r.length, 0), 'points');
}
source += '}\n';
fs.writeFileSync(OUT, source);
