extends RefCounted

# One short, playful intro line per landmark, shown on the city's first start
# (intro.gd landmark_tip) and again when it is swallowed. Columns follow
# I18n.LANGS: vi, en, es, pt, fr, id. Kept apart from i18n_strings.gd for size.
const S := {
	# --- Asia ---
	"lmfun_onepillar": ["Cả ngôi chùa đứng trên một cột. Đúng một cột thôi. Run chưa?", "A whole pagoda on ONE pillar. Talk about balance goals.", "Una pagoda entera sobre UN pilar. ¡Qué equilibrio!", "Um pagode inteiro sobre UM pilar. Que equilíbrio!", "Une pagode entière sur UN pilier. Quel équilibre !", "Satu pagoda di atas SATU pilar. Keseimbangan sejati!"],
	"lmfun_namsan": ["Ngọn tháp gắn ổ khóa tình yêu. Nuốt luôn cả chìa nhé!", "The tower covered in love locks. Swallow the keys too!", "La torre de los candados del amor. ¡Trágate las llaves!", "A torre dos cadeados do amor. Engula as chaves também!", "La tour aux cadenas d’amour. Avale aussi les clés !", "Menara gembok cinta. Telan kuncinya juga!"],
	"lmfun_khuevan": ["Biểu tượng của Hà Nội, nơi sĩ tử cầu đỗ. Ta thì cầu… no.", "Hanoi’s icon, where students pray to pass exams. You just pray to be full.", "Icono de Hanói donde los estudiantes rezan por aprobar. Tú, por llenarte.", "Ícone de Hanói onde estudantes rezam para passar. Você reza para encher.", "Icône de Hanoï où l’on prie pour réussir. Toi, pour te remplir.", "Ikon Hanoi tempat pelajar berdoa lulus. Kamu berdoa kenyang."],
	"lmfun_watarun": ["Ngôi chùa lấp lánh gốm sứ. Giòn rụm như bánh quy!", "A temple sparkling with porcelain. Crunchy like a cookie!", "Un templo brillante de porcelana. ¡Crujiente como galleta!", "Um templo brilhando de porcelana. Crocante como biscoito!", "Un temple scintillant de porcelaine. Croquant comme un biscuit !", "Kuil berkilau porselen. Renyah seperti biskuit!"],
	"lmfun_taj": ["Lăng mộ đẹp nhất thế giới. Đẹp thế này ăn có tiếc không?", "The world’s prettiest monument. Almost too pretty to eat. Almost.", "El monumento más bello del mundo. Casi demasiado para comérselo.", "O monumento mais lindo do mundo. Quase lindo demais para comer.", "Le plus beau monument du monde. Presque trop beau pour être mangé.", "Monumen tercantik di dunia. Hampir terlalu cantik untuk dimakan."],
	"lmfun_pearl": ["Tháp có những viên ngọc hồng khổng lồ. Kẹo mút size đại!", "A tower of giant pink pearls. Basically a lollipop kebab!", "Una torre de perlas rosas gigantes. ¡Un pincho de piruletas!", "Uma torre de pérolas rosa gigantes. Um espeto de pirulitos!", "Une tour de perles roses géantes. Une brochette de sucettes !", "Menara mutiara merah muda raksasa. Sate permen lolipop!"],
	"lmfun_fuji": ["Núi Phú Sĩ đội mũ tuyết quanh năm. Như kem ốc quế vậy!", "Mount Fuji wears a snow cap all year. A giant ice-cream cone!", "El Fuji lleva gorro de nieve todo el año. ¡Un cucurucho gigante!", "O Fuji usa gorro de neve o ano todo. Um sorvete gigante!", "Le Fuji porte un bonnet de neige. Un cornet de glace géant !", "Fuji pakai topi salju sepanjang tahun. Es krim cone raksasa!"],
	"lmfun_tokyotower": ["Tháp Tokyo màu cam trắng, nhái tháp Eiffel mà còn cao hơn!", "Tokyo Tower: an orange Eiffel copy that’s actually taller!", "La Torre de Tokio: una Eiffel naranja ¡y más alta!", "Torre de Tóquio: uma Eiffel laranja e ainda mais alta!", "La tour de Tokyo : une Eiffel orange… et plus haute !", "Menara Tokyo: Eiffel versi oranye yang lebih tinggi!"],
	# --- Europe ---
	"lmfun_eiffel": ["Hơn 18.000 thanh sắt. Ăn vào chắc bổ sung sắt lắm!", "Over 18,000 iron parts. Great source of iron!", "Más de 18.000 piezas de hierro. ¡Mucho hierro en la dieta!", "Mais de 18 mil peças de ferro. Rico em ferro!", "Plus de 18 000 pièces de fer. Riche en fer !", "Lebih dari 18.000 bagian besi. Kaya zat besi!"],
	"lmfun_bigben": ["Big Ben điểm giờ chuẩn từng giây. Giờ ăn trưa tới rồi!", "Big Ben keeps perfect time. And it says: lunchtime!", "El Big Ben da la hora exacta. Y marca: ¡hora de comer!", "O Big Ben marca a hora certa. E diz: hora do almoço!", "Big Ben donne l’heure exacte. Et il dit : l’heure du repas !", "Big Ben selalu tepat waktu. Dan katanya: waktunya makan!"],
	"lmfun_pisa": ["Tháp nghiêng sẵn rồi, chỉ cần đẩy nhẹ vào miệng thôi.", "It’s already leaning. Just nudge it into your mouth.", "Ya está inclinada. Solo empújala hacia tu boca.", "Ela já está inclinada. Só empurre para a sua boca.", "Elle penche déjà. Pousse-la juste vers ta bouche.", "Sudah miring. Tinggal dorong ke mulutmu."],
	"lmfun_colosseum": ["Đấu trường 2.000 tuổi. Hôm nay nó đấu với… cái hố.", "A 2,000-year-old arena. Today’s challenger: a hole.", "Una arena de 2.000 años. El rival de hoy: un agujero.", "Uma arena de 2.000 anos. O desafiante de hoje: um buraco.", "Une arène de 2 000 ans. Le challenger du jour : un trou.", "Arena 2.000 tahun. Penantang hari ini: sebuah lubang."],
	"lmfun_brandenburg": ["Cổng Brandenburg: cửa vào Berlin. Và vào bụng ta.", "Brandenburg Gate: the door to Berlin. And to your belly.", "La Puerta de Brandeburgo: entrada a Berlín. Y a tu barriga.", "Portão de Brandemburgo: entrada de Berlim. E da sua barriga.", "La porte de Brandebourg : entrée de Berlin. Et de ton ventre.", "Gerbang Brandenburg: pintu Berlin. Dan pintu perutmu."],
	"lmfun_alcala": ["Cổng Alcalá cổ kính giữa Madrid. Olé, măm măm!", "Madrid’s grand Alcalá Gate. Olé, nom nom!", "La Puerta de Alcalá en pleno Madrid. ¡Olé y ñam ñam!", "A Porta de Alcalá em Madri. Olé, nham nham!", "La porte d’Alcalá à Madrid. Olé, miam miam !", "Gerbang Alcalá di Madrid. Olé, nyam nyam!"],
	"lmfun_royalpalace": ["Cung điện hơn 3.000 phòng. Một bữa buffet hoàng gia!", "A palace with 3,000+ rooms. A royal buffet!", "Un palacio de más de 3.000 salas. ¡Un bufé real!", "Um palácio com mais de 3 mil salas. Um bufê real!", "Un palais de plus de 3 000 pièces. Un buffet royal !", "Istana 3.000+ ruangan. Prasmanan kerajaan!"],
	"lmfun_stbasils": ["Mái vòm như kem xoắn nhiều vị. Tráng miệng đây rồi!", "Domes like swirly ice cream. Dessert is served!", "Cúpulas como helado en espiral. ¡El postre está servido!", "Cúpulas que parecem sorvete. A sobremesa chegou!", "Des dômes comme des glaces à l’italienne. Le dessert !", "Kubah seperti es krim berpilin. Hidangan penutup!"],
	# --- Africa ---
	"lmfun_pyramid": ["4.500 năm tuổi, hai triệu khối đá. Món này hơi dai.", "4,500 years old, two million stones. A bit chewy.", "4.500 años y dos millones de piedras. Algo duro de masticar.", "4.500 anos e dois milhões de pedras. Meio duro de mastigar.", "4 500 ans, deux millions de pierres. Un peu coriace.", "4.500 tahun, dua juta batu. Agak alot."],
	"lmfun_sphinx": ["Nhân Sư hỏi câu đố: “Cái gì ăn cả thành phố?” Là ta!", "The Sphinx asks: “What eats whole cities?” You do!", "La Esfinge pregunta: “¿Qué se come ciudades?” ¡Tú!", "A Esfinge pergunta: “O que come cidades?” Você!", "Le Sphinx demande : « Qui mange des villes ? » Toi !", "Sphinx bertanya: “Apa yang makan kota?” Kamu!"],
	"lmfun_cairotower": ["Tháp Cairo như bông sen khổng lồ. Gỏi ngó sen nhé!", "Cairo Tower is shaped like a lotus. Lotus salad, anyone?", "La Torre de El Cairo es un loto gigante. ¿Ensalada de loto?", "A Torre do Cairo é um lótus gigante. Salada de lótus?", "La tour du Caire est un lotus géant. Salade de lotus ?", "Menara Kairo berbentuk teratai. Salad teratai?"],
	"lmfun_djenne": ["Thánh đường lớn nhất thế giới làm từ… bùn. Bánh bùn đặc sản!", "The world’s biggest mud building. A local mud pie!", "El mayor edificio de barro del mundo. ¡Pastel de barro!", "O maior prédio de barro do mundo. Torta de barro!", "Le plus grand bâtiment en terre. Une tarte de boue !", "Bangunan lumpur terbesar di dunia. Kue lumpur khas!"],
	"lmfun_baobab": ["Cây baobab sống cả nghìn năm. Gặp ta thì hết sống!", "Baobabs live a thousand years. Until they meet you.", "Los baobabs viven mil años. Hasta que te conocen.", "Baobás vivem mil anos. Até conhecerem você.", "Les baobabs vivent mille ans. Jusqu’à ta venue.", "Baobab hidup seribu tahun. Sampai bertemu kamu."],
	"lmfun_kicc": ["Tháp KICC có mái như chiếc nón. Đội luôn cho đẹp!", "KICC Tower wears a hat-shaped roof. Stylish snack!", "La torre KICC lleva un techo-sombrero. ¡Snack con estilo!", "A torre KICC tem um telhado de chapéu. Lanche estiloso!", "La tour KICC porte un toit-chapeau. Un snack stylé !", "Menara KICC beratap seperti topi. Camilan bergaya!"],
	"lmfun_nationaltheatre": ["Nhà hát hình chiếc mũ quân đội. Hết vở diễn rồi!", "A theatre shaped like a military hat. Show’s over!", "Un teatro con forma de gorra militar. ¡Se acabó la función!", "Um teatro em forma de quepe. Fim do espetáculo!", "Un théâtre en forme de képi. Fin du spectacle !", "Teater berbentuk topi militer. Pertunjukan selesai!"],
	"lmfun_tablemountain": ["Núi Bàn phẳng như cái bàn. Dọn bàn ăn thôi!", "Table Mountain is flat as a table. Dinner is served!", "La Montaña de la Mesa es plana. ¡La cena está servida!", "A Montanha da Mesa é plana. O jantar está servido!", "La montagne de la Table est plate. À table !", "Gunung Meja rata seperti meja. Waktunya makan!"],
	# --- North America ---
	"lmfun_liberty": ["Bà giơ đuốc suốt 140 năm. Cuối cùng cũng được hạ tay!", "She held that torch for 140 years. Time to rest her arm!", "Sostuvo la antorcha 140 años. ¡Hora de bajar el brazo!", "Segurou a tocha por 140 anos. Hora de descansar o braço!", "Elle tient sa torche depuis 140 ans. Enfin du repos !", "Memegang obor 140 tahun. Akhirnya bisa istirahat!"],
	"lmfun_empire": ["102 tầng, King Kong từng leo. Ta thì xơi từ dưới lên!", "102 floors, King Kong climbed it. You go from below!", "102 pisos, King Kong la escaló. ¡Tú vas desde abajo!", "102 andares, o King Kong escalou. Você vai por baixo!", "102 étages, King Kong l’a grimpé. Toi, par en dessous !", "102 lantai, King Kong memanjatnya. Kamu dari bawah!"],
	"lmfun_needle": ["Space Needle trông như đĩa bay. Đồng hương đây rồi!", "The Space Needle looks like a UFO. Hello, cousin!", "La Space Needle parece un ovni. ¡Hola, primo!", "A Space Needle parece um óvni. Olá, primo!", "La Space Needle ressemble à un OVNI. Salut, cousin !", "Space Needle mirip UFO. Halo, sepupu!"],
	"lmfun_chichen": ["Vỗ tay dưới chân tháp sẽ nghe tiếng chim. Ta thì nghe tiếng… nhai.", "Clap at its base and it chirps like a bird. You’ll hear munching.", "Aplaude al pie y suena como un pájaro. Tú oirás masticar.", "Bata palmas na base e soa como pássaro. Você ouvirá mastigar.", "Tape des mains : ça gazouille. Toi, tu entendras croquer.", "Tepuk tangan di kakinya terdengar burung. Kamu dengar kunyahan."],
	"lmfun_willis": ["Có ban công kính lơ lửng tầng 103. Ai sợ độ cao không?", "It has glass boxes on floor 103. Afraid of heights?", "Tiene balcones de cristal en el piso 103. ¿Vértigo?", "Tem caixas de vidro no 103º andar. Medo de altura?", "Des balcons de verre au 103e étage. Le vertige ?", "Ada balkon kaca di lantai 103. Takut ketinggian?"],
	"lmfun_cntower": ["Tháp CN cao 553 m. Món que xiên dài nhất Canada!", "The CN Tower is 553 m tall. Canada’s longest skewer!", "La Torre CN mide 553 m. ¡El pincho más largo de Canadá!", "A Torre CN tem 553 m. O maior espeto do Canadá!", "La tour CN fait 553 m. La plus longue brochette du Canada !", "Menara CN setinggi 553 m. Tusuk sate terpanjang Kanada!"],
	"lmfun_hollywood": ["Dòng chữ nổi tiếng nhất thế giới. Ăn từng chữ cái nhé!", "The world’s most famous sign. Eat it letter by letter!", "El cartel más famoso del mundo. ¡Cómetelo letra a letra!", "O letreiro mais famoso do mundo. Coma letra por letra!", "Le panneau le plus célèbre du monde. Lettre par lettre !", "Tulisan paling terkenal di dunia. Makan huruf demi huruf!"],
	"lmfun_capitol": ["Mái vòm trắng như bánh bao khổng lồ. Hấp nóng đây!", "A white dome like a giant steamed bun. Piping hot!", "Una cúpula blanca como un bollo gigante. ¡Recién hecho!", "Uma cúpula branca como um pão gigante. Quentinho!", "Un dôme blanc comme une brioche géante. Tout chaud !", "Kubah putih seperti bakpao raksasa. Masih hangat!"],
	# --- South America ---
	"lmfun_christ": ["Tượng Chúa dang tay chào đón. Đón luôn cả cái hố đói!", "Arms wide open to welcome you. Even a hungry hole!", "Brazos abiertos para recibirte. ¡Incluso a un agujero!", "Braços abertos para receber você. Até um buraco faminto!", "Bras grands ouverts pour t’accueillir. Même un trou affamé !", "Tangan terbuka menyambutmu. Bahkan lubang lapar!"],
	"lmfun_machu": ["Thành phố trên mây của người Inca. Lạc đà alpaca làm tráng miệng!", "The Inca city in the clouds. With alpacas for dessert!", "La ciudad inca entre nubes. ¡Con alpacas de postre!", "A cidade inca nas nuvens. Com alpacas de sobremesa!", "La cité inca dans les nuages. Des alpagas en dessert !", "Kota Inca di atas awan. Alpaka sebagai penutup!"],
	"lmfun_obelisco": ["Đài Obelisco cao vút như cây bút chì. Vừa gọt xong!", "The Obelisco looks like a giant pencil. Freshly sharpened!", "El Obelisco parece un lápiz gigante. ¡Recién afilado!", "O Obelisco parece um lápis gigante. Recém-apontado!", "L’Obélisque ressemble à un crayon géant. Bien taillé !", "Obelisco mirip pensil raksasa. Baru diraut!"],
	"lmfun_sugarloaf": ["Núi Bánh Đường. Nghe tên là thấy ngọt rồi!", "Sugarloaf Mountain. Even the name sounds tasty!", "El Pan de Azúcar. ¡Hasta el nombre es dulce!", "O Pão de Açúcar. Até o nome é doce!", "Le Pain de Sucre. Même le nom est sucré !", "Gunung Roti Gula. Namanya saja sudah manis!"],
	"lmfun_masp": ["Bảo tàng lơ lửng trên bốn cột đỏ. Như cái bàn ăn khổng lồ!", "A museum floating on four red legs. A giant dinner table!", "Un museo sobre cuatro patas rojas. ¡Una mesa gigante!", "Um museu sobre quatro pernas vermelhas. Uma mesa gigante!", "Un musée sur quatre pieds rouges. Une table géante !", "Museum di atas empat kaki merah. Meja makan raksasa!"],
	"lmfun_limacathedral": ["Nhà thờ Lima gần 500 tuổi. Đồ cổ thì càng đậm vị!", "Lima Cathedral is almost 500 years old. Aged to perfection!", "La catedral de Lima tiene casi 500 años. ¡Bien añejada!", "A catedral de Lima tem quase 500 anos. Bem envelhecida!", "La cathédrale de Lima a presque 500 ans. Bien affinée !", "Katedral Lima hampir 500 tahun. Makin tua makin nikmat!"],
	"lmfun_monserrate": ["Đồi Monserrate cao 3.152 m. Lười leo thì ăn luôn!", "Monserrate hill is 3,152 m high. Eat it instead of climbing!", "El cerro Monserrate mide 3.152 m. ¡Mejor cómetelo!", "O morro Monserrate tem 3.152 m. Melhor comer que subir!", "Le mont Monserrate culmine à 3 152 m. Mange-le plutôt !", "Bukit Monserrate 3.152 m. Lebih baik dimakan daripada didaki!"],
	"lmfun_costanera": ["Tòa nhà cao nhất Nam Mỹ. Một miếng là xong!", "South America’s tallest building. One big bite!", "El edificio más alto de Sudamérica. ¡De un bocado!", "O prédio mais alto da América do Sul. Numa mordida só!", "Le plus haut gratte-ciel d’Amérique du Sud. En une bouchée !", "Gedung tertinggi Amerika Selatan. Sekali gigit!"],
	# --- Oceania ---
	"lmfun_sydney": ["Mái nhà hát như vỏ sò. Hải sản tươi sống đây!", "Roofs like seashells. Fresh seafood!", "Techos como conchas. ¡Marisco fresco!", "Telhados como conchas. Frutos do mar frescos!", "Des toits comme des coquillages. Fruits de mer frais !", "Atap seperti kerang. Makanan laut segar!"],
	"lmfun_uluru": ["Đá Uluru đổi màu lúc hoàng hôn. Như bánh nướng chín vàng!", "Uluru changes colour at sunset. Like a perfectly baked pie!", "Uluru cambia de color al atardecer. ¡Como un pastel al horno!", "Uluru muda de cor ao pôr do sol. Como uma torta assada!", "Uluru change de couleur au coucher du soleil. Comme une tarte !", "Uluru berubah warna saat senja. Seperti kue matang!"],
	"lmfun_skytower": ["Người ta nhảy bungee từ Sky Tower. Ta thì cho nhảy thẳng vào bụng!", "People bungee jump off the Sky Tower. Straight into your belly!", "La gente salta en bungee desde la Sky Tower. ¡A tu barriga!", "Pessoas saltam de bungee da Sky Tower. Direto na barriga!", "On saute à l’élastique de la Sky Tower. Droit dans ton ventre !", "Orang bungee dari Sky Tower. Langsung ke perutmu!"],
	"lmfun_moai": ["Tượng Moai mặt nghiêm nghị. Cười lên nào, sắp vào bụng rồi!", "The Moai look so serious. Smile, you’re about to be eaten!", "Los moáis son muy serios. ¡Sonríe, que te van a comer!", "Os moais são sérios. Sorria, você vai ser comido!", "Les moaï ont l’air sérieux. Souriez, vous allez être mangés !", "Moai terlihat serius. Senyum, kamu akan dimakan!"],
	"lmfun_flinders": ["Ga Flinders với hàng đồng hồ nổi tiếng. Đến giờ ăn rồi!", "Flinders Station and its famous clocks. They all say: snack time!", "La estación Flinders y sus relojes. ¡Todos marcan la merienda!", "Estação Flinders e seus relógios. Todos dizem: hora do lanche!", "La gare Flinders et ses horloges. Toutes disent : goûter !", "Stasiun Flinders dan jam-jamnya. Semua bilang: waktu camilan!"],
	"lmfun_belltower": ["Tháp chuông Perth có 18 quả chuông. Ăn xong nhớ rung chuông!", "Perth’s Bell Tower has 18 bells. Ring them when you’re full!", "La torre de Perth tiene 18 campanas. ¡Tócalas al terminar!", "A torre de Perth tem 18 sinos. Toque-os quando estiver cheio!", "Le clocher de Perth a 18 cloches. Sonne-les une fois repu !", "Menara Lonceng Perth punya 18 lonceng. Bunyikan saat kenyang!"],
	"lmfun_fijitemple": ["Ngôi đền rực rỡ sắc màu. Như hộp kẹo đầy màu sắc!", "A temple bursting with colours. Like a box of candy!", "Un templo lleno de colores. ¡Como una caja de caramelos!", "Um templo cheio de cores. Como uma caixa de doces!", "Un temple plein de couleurs. Comme une boîte de bonbons !", "Kuil penuh warna. Seperti sekotak permen!"],
	"lmfun_parliament": ["Nhà Quốc hội được gọi là Tổ Ong. Ngọt như mật!", "This Parliament is called the Beehive. Sweet as honey!", "A este parlamento lo llaman la Colmena. ¡Dulce como miel!", "Este parlamento é chamado de Colmeia. Doce como mel!", "Ce parlement s’appelle la Ruche. Doux comme le miel !", "Gedung parlemen ini disebut Sarang Lebah. Manis seperti madu!"],
}
